# Generated by Django 5.2.7 on 2025-10-23 11:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_alter_claim_options_alter_member_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claim',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='memberpayment',
            options={},
        ),
        migrations.RemoveField(
            model_name='claim',
            name='member',
        ),
        migrations.RemoveField(
            model_name='member',
            name='policy',
        ),
        migrations.RemoveField(
            model_name='memberpayment',
            name='member',
        ),
        migrations.RemoveField(
            model_name='memberpayment',
            name='policy',
        ),
        migrations.AddField(
            model_name='member',
            name='national_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='memberpayment',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memberpayment',
            name='transaction_id',
            field=models.CharField(default=uuid.uuid4, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='MemberPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_policies', to='insurance.member')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_policies', to='insurance.policy')),
            ],
            options={
                'verbose_name': 'Member Policy',
                'verbose_name_plural': 'Member Policies',
                'unique_together': {('member', 'policy')},
            },
        ),
        migrations.AddField(
            model_name='claim',
            name='member_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='insurance.memberpolicy'),
        ),
        migrations.AddField(
            model_name='member',
            name='policies',
            field=models.ManyToManyField(related_name='members', through='insurance.MemberPolicy', to='insurance.policy'),
        ),
        migrations.AddField(
            model_name='memberpayment',
            name='member_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='insurance.memberpolicy'),
        ),
        migrations.DeleteModel(
            name='HospitalPayment',
        ),
    ]
