# Generated by Django 5.2.7 on 2025-10-23 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0004_claimdocument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policy',
            options={},
        ),
        migrations.RenameField(
            model_name='memberpolicy',
            old_name='joined_date',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='member',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='member',
            name='national_id',
        ),
        migrations.RemoveField(
            model_name='member',
            name='policies',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='created_at',
        ),
        migrations.AddField(
            model_name='memberpolicy',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberpolicy',
            name='member_policy_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='memberpolicy',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='insurance.member'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired')], default='active', max_length=20),
        ),
    ]
