# Generated by Django 5.2.7 on 2025-10-23 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0005_alter_policy_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
